server:
  port: 9000

spring:
  profile:
    active: dev
---
spring:
  profiles: dev
  application:
    name: inventory-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_auth
    username: spring_user
    password: springuser
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

---

spring:
  profiles: test
  application:
    name: inventory-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_test
    username: spring_user
    password: springuser
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create