name: Continuous Deployment Workflow for Inventory Tracker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Build and Package the Spring Boot Application
        run: mvn clean package -DskipTests

      - name: List files in target directory
        run: ls -al target/

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Check if Java is installed
            if ! command -v java &> /dev/null
            then
              echo "Java not found, installing JDK 17..."
              sudo yum update -y
              sudo yum install java-17-amazon-corretto -y
            else
              echo "Java is already installed."
            fi
  
            # Stop the Spring Boot service if it's running
            sudo systemctl stop inventory-tracker || true
  
            # Remove the old jar file
            rm -f /home/ec2-user/inventory-tracker.jar
  
            # Copy the new jar to the correct location
            echo "Moving new jar file to /home/ec2-user/inventory-tracker.jar"
            mv target/*.jar /home/ec2-user/inventory-tracker.jar          
            
            # Restart the Spring Boot service using systemd
            sudo systemctl start inventory-tracker