name: Continuous Deployment Workflow for Inventory Tracker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Build and Package the Spring Boot Application
        run: mvn clean package -DskipTests

      - name: List files in target directory
        run: ls -al target/

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop the existing application
            sudo systemctl stop inventory-tracker.service || true
            
            # Transfer the JAR file or pull the Docker image
            # If deploying JAR directly:
            scp target/*.jar /home/ec2-user/inventory-tracker.jar
            
            # Restart the application service
            sudo systemctl start inventory-tracker.service