name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration Workflow for Inventory Tracker"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: inventory-tracker-jar
          path: ./app