name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration Workflow for Inventory Tracker"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: List files in target/
        run: ls -R target/

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: inventory-tracker-jar
          path: ./app